### ISSUE TITLE
Tracker for documentation tasks

### ISSUE THREAD

**Issue by abelcheung** [abelcheung/types-lxml#15]
## Wiki
- [x] `_Element` inheritance, changes in `HtmlElement` and friends
  - [ ] Docuemnt how to do type narrowing with examples
- ~~`ParserTarget` usage~~ (support is forfeited)
- [x] `SmartStr` usage
- [x] Keep status quo for PlantUML diagrams (use gist + raw.githubusercontent.com) ~~or place everything under wiki git repo~~
- [x] Usage of subscripted types where it is actually unsupported in concrete classes, like `_ElementTree[_Element]` (abelcheung/types-lxml#14)

**Comment by abelcheung** [comment]
Will use GitHub Projects to track such future tasks, thus this tracker issue can be retired.
