### ISSUE TITLE
Retire _AnyStr and add buffer-like doc support

### ISSUE THREAD

**Issue by abelcheung** [abelcheung/types-lxml#71]
The alias `_AnyStr` has been traditionally used inside `lxml-stubs` to mean `str | bytes`, even before being [cut off from `typeshed`](https://github.com/python/typeshed/commit/735abe68dd8ea19adf568b12e28b7477f15ee6f7). There isn't a big motivation yet to eliminate its usage so far, despite being easily confusable with `typing.AnyStr`.

Now that `typing.AnyStr` has been [officially deprecated](https://docs.python.org/3/library/typing.html#deprecation-timeline-of-major-features), and `types-lxml` is trying to update arguments where `bytearray` is applicable, the time might be appropriate to have `_AnyStr` gone for good. Even if an alias is desired, something like `TextArg` makes more sense and less likely mistaken as the deprecated `TypeVar`.

### Tasks ahead

- [x] Search for places where `_AnyStr` is used for single purpose
	- [x] attribute value comes to mind, especially inside `SupportsLaxedItems` mapping (233adc910ecd64ee86bd2b95e53f7400c1848860)
- [x] For remaining usages, slowly test for `bytearray` and replace arguments
    - [x] (#82) `Lxml 6.0` has incorporated support of `memoryview` in `_parseDoc()`, it should be reflected in annotation as well.
- [x] Maybe really create a `TextArg` alias for this purpose (894e2bad9d4891a04a713d16788c78380d8c3b4c)
